### ISSUE TITLE
Profile obsolete?

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.folder#2]
From what i see the profile is never loaded. Is it meanwhile obsolete?

- in which metadata.xml is a dependency on this profile?
- gopip Index is added in Products.CMFPlone
- the type defintion is not used - we have dexterity now - whats the story in atct?

**Comment by gforcada** [comment]
I'm trying to remove it but on ``p.a.f/testing/layer.py`` it explicitly loads the profile to check that ``Folder`` is a ``plone.app.folder`` instead of ``ATContentTypes``.

I just removed the check for it alltogether and tests seem to pass (locally), see the PR #8

**Comment by gforcada** [comment]
Removed!
